import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useWeb3React } from "@web3-react/core";
import { InjectedConnector } from "@web3-react/injected-connector";
import { ethers } from 'ethers';
import { Button, Navbar, Container, Nav } from 'react-bootstrap';
import { useEffect } from "react"

const injected = new InjectedConnector()

export default function NavBar() {
  const { activate, active, library: provider } = useWeb3React();
  useEffect(() => {

  }, [])

  const connect = async () => {
    try {
      await activate(injected)
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar variant="dark" bg="dark">
        {/* https://drive.google.com/file/d/1848FBXTqPIYWHVmtFIoPbM95cjhHcBH4/view?usp=sharing */}
        <Container>
          <Navbar.Brand href="/">
            <img
            alt=""
            src="https://drive.google.com/uc?export=view&id=1848FBXTqPIYWHVmtFIoPbM95cjhHcBH4"
            width="30"
            height="30"
            className="d-inline-block align-top"
          />{' '} TASK IT
          </Navbar.Brand>
          <Navbar.Toggle />
          <Navbar.Collapse className="justify-content-end">
          <Nav className="me-auto">
            <Nav.Link href="/JobUploads">Upload Service</Nav.Link>
            <Nav.Link href="/WorkHistory">Work History</Nav.Link>
          </Nav>
            <Navbar.Text>
              <img
              alt=""
              src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/MetaMask_Fox.svg/1200px-MetaMask_Fox.svg.png"
              width="30"
              height="30"
              className="d-inline-block align-top"
            />{' '}:  {'   '}{active ? <Button size='sm'>Metamask Connected</Button> : (
              <Button variant="outline-primary" size='sm' onClick={() => connect()}>Connect</Button>
            )}
            </Navbar.Text>
          </Navbar.Collapse>
        </Container>
      </Navbar>

    </div>
  )
}