import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useWeb3React } from "@web3-react/core";
import { InjectedConnector } from "@web3-react/injected-connector";
import { ethers } from 'ethers';
import { Button, Navbar, Container } from 'react-bootstrap';
import { useEffect } from "react"

const injected = new InjectedConnector()

export default function Home() {
  const { activate, active, library: provider } = useWeb3React();
  useEffect(() => {

  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Anonymous</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          Anonymous
        </h1>
      </main>


    </div>
  )
}